    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
		<base href="<?php echo APP_URL; ?>" target="_blank" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- Titulo -->
    <title><?php echo APP_TITLE; ?></title>
    <!-- Bootstrap -->
    <link href="views/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="views/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
		<!-- NProgress -->
		<link href="views/vendors/nprogress/nprogress.css" rel="stylesheet">
		<!-- Datatables -->
		<link href="views/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
		<!-- Alertify -->
		<link rel="stylesheet" href="views/build/alertify/themes/alertify.core.css" />
		<link rel="stylesheet" href="views/build/alertify/themes/alertify.default.css" id="toggleCSS" />
    <!-- Custom Theme Style -->
    <link href="views/build/css/custom.min.css" rel="stylesheet">
