<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
	<div class="menu_section">
		<h3>General</h3>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-user"></i> Empleado <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
						<li><a href="javascript:void(0);" id="addempleado">Agregar</a></li>
						<li><a href="javascript:void(0);" id="buscarempleado">Buscar</a></li>
				</ul>
			</li>
		</ul>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-bug"></i>Agregar Datos<span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a  href="javascript:void(0);" id="plaza">Plazas</a></li>
					<li><a href="javascript:void(0);" id="departamento">Departamentos</a></li>
					<li><a  href="javascript:void(0);" id="centroTrabajo">Centro de Trabajo</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>
