<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
	<div class="menu_section">
		<h3>General</h3>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-user"></i> Empleado <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="javascript:void(0);" id="addempleado">Agregar</a></li>
					<li><a href="javascript:void(0);" id="updateempleado">Acutalizar</a></li>
					<li><a href="javascript:void(0);">Buscar</a></li>
				</ul>
			</li>
		</ul>
	</div>
	<div class="menu_section">
		<h3>Live On</h3>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-bug"></i> Plaza <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a  href="javascript:void(0);" id="plaza">Configuración</a></li>
				</ul>
			</li>
		</ul>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-bug"></i> Centro de trabajo <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a  href="javascript:void(0);" id="centroTrabajo">Configuración</a></li>
				</ul>
			</li>
		</ul>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-bug"></i> Departamentos <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="javascript:void(0);" id="departamento">Departamento</a></li>
				</ul>
			</li>
		</ul>
	</div>
	<div class="menu_section">
		<h3>Config</h3>
		<ul class="nav side-menu">
		</ul>
	</div>

</div>
