<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
	<div class="menu_section">
		<h3>General</h3>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-home"></i> Inicio <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="javascript:void(0);" id="home">Bienvenida</a></li>
				</ul>
			</li>
			<li><a><i class="fa fa-user"></i> Empleado <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="javascript:void(0);" >Agregar</a></li>
					<li><a href="<?php echo HTML_DIR; ?>views/empleado_update.php">Acutalizar</a></li>
					<li><a href="<?php echo HTML_DIR; ?>views/base.php">Buscar</a></li>
				</ul>
			</li>
			<li><a><i class="fa fa-desktop"></i> Delegados <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="javascript:void(0);" id="delegado">Delegados</a></li>
				</ul>
			</li>
		</ul>
	</div>
	<div class="menu_section">
		<h3>Live On</h3>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-bug"></i> Categorias <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a  href="javascript:void(0);" id="categoria">Configuración</a></li>
				</ul>
			</li>
		</ul>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-bug"></i> Centro de trabajo <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a  href="javascript:void(0);" id="centrab">Configuración</a></li>
				</ul>
			</li>
		</ul>
		<ul class="nav side-menu">
			<li><a><i class="fa fa-bug"></i> Departamentos <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="<?php echo HTML_DIR; ?>views/departamentos.php">E-commerce</a></li>
					<li><a href="<?php echo HTML_DIR; ?>views/tipo_permiso.php">Tipo de permiso</a></li>
				</ul>
			</li>
		</ul>
	</div>
	<div class="menu_section">
		<h3>Config</h3>
		<ul class="nav side-menu">

			</li>
		</ul>
	</div>

</div>
